/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LFeiPairInterface extends ethers.utils.Interface {
  functions: {
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "claimFees()": FunctionFragment;
    "contractCreator()": FunctionFragment;
    "conversionRateNumerator()": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "denominator()": FunctionFragment;
    "depositFei(uint256)": FunctionFragment;
    "feesEarned()": FunctionFragment;
    "fei()": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "swap(uint256,address,bytes)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "usdc()": FunctionFragment;
    "usdcFeesNumerator()": FunctionFragment;
    "withdrawFei(uint256)": FunctionFragment;
    "withdrawUSDC(uint256)": FunctionFragment;
    "withdrawableFei(address)": FunctionFragment;
    "withdrawableUSDC(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "claimFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contractCreator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conversionRateNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "denominator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFei",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feesEarned",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fei", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcFeesNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFei",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableFei",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableUSDC",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conversionRateNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "denominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feesEarned", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fei", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcFeesNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableFei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableUSDC",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class LFeiPair extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LFeiPairInterface;

  functions: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    claimFees(overrides?: Overrides): Promise<ContractTransaction>;

    "claimFees()"(overrides?: Overrides): Promise<ContractTransaction>;

    contractCreator(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "contractCreator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    conversionRateNumerator(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "conversionRateNumerator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    decimals(
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "decimals()"(
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    denominator(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "denominator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    depositFei(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "depositFei(uint256)"(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    feesEarned(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "feesEarned()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    fei(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "fei()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    name(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "name()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    swap(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swap(uint256,address,bytes)"(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    symbol(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "symbol()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    totalSupply(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "totalSupply()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    usdc(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "usdc()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    usdcFeesNumerator(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "usdcFeesNumerator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    withdrawFei(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawFei(uint256)"(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawUSDC(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawUSDC(uint256)"(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawableFei(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "withdrawableFei(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    withdrawableUSDC(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "withdrawableUSDC(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimFees(overrides?: Overrides): Promise<ContractTransaction>;

  "claimFees()"(overrides?: Overrides): Promise<ContractTransaction>;

  contractCreator(overrides?: CallOverrides): Promise<string>;

  "contractCreator()"(overrides?: CallOverrides): Promise<string>;

  conversionRateNumerator(overrides?: CallOverrides): Promise<BigNumber>;

  "conversionRateNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decreaseAllowance(address,uint256)"(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  denominator(overrides?: CallOverrides): Promise<BigNumber>;

  "denominator()"(overrides?: CallOverrides): Promise<BigNumber>;

  depositFei(
    amountFeiIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "depositFei(uint256)"(
    amountFeiIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  feesEarned(overrides?: CallOverrides): Promise<BigNumber>;

  "feesEarned()"(overrides?: CallOverrides): Promise<BigNumber>;

  fei(overrides?: CallOverrides): Promise<string>;

  "fei()"(overrides?: CallOverrides): Promise<string>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseAllowance(address,uint256)"(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  swap(
    amountFeiOut: BigNumberish,
    to: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swap(uint256,address,bytes)"(
    amountFeiOut: BigNumberish,
    to: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  usdc(overrides?: CallOverrides): Promise<string>;

  "usdc()"(overrides?: CallOverrides): Promise<string>;

  usdcFeesNumerator(overrides?: CallOverrides): Promise<BigNumber>;

  "usdcFeesNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawFei(
    amountFeiOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawFei(uint256)"(
    amountFeiOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawUSDC(
    amountUSDCOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawUSDC(uint256)"(
    amountUSDCOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawableFei(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "withdrawableFei(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawableUSDC(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "withdrawableUSDC(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFees(overrides?: CallOverrides): Promise<void>;

    "claimFees()"(overrides?: CallOverrides): Promise<void>;

    contractCreator(overrides?: CallOverrides): Promise<string>;

    "contractCreator()"(overrides?: CallOverrides): Promise<string>;

    conversionRateNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "conversionRateNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    denominator(overrides?: CallOverrides): Promise<BigNumber>;

    "denominator()"(overrides?: CallOverrides): Promise<BigNumber>;

    depositFei(
      amountFeiIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositFei(uint256)"(
      amountFeiIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    feesEarned(overrides?: CallOverrides): Promise<BigNumber>;

    "feesEarned()"(overrides?: CallOverrides): Promise<BigNumber>;

    fei(overrides?: CallOverrides): Promise<string>;

    "fei()"(overrides?: CallOverrides): Promise<string>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    swap(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "swap(uint256,address,bytes)"(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    usdc(overrides?: CallOverrides): Promise<string>;

    "usdc()"(overrides?: CallOverrides): Promise<string>;

    usdcFeesNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "usdcFeesNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFei(
      amountFeiOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawFei(uint256)"(
      amountFeiOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawUSDC(
      amountUSDCOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawUSDC(uint256)"(
      amountUSDCOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawableFei(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdrawableFei(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawableUSDC(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdrawableUSDC(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;
  };

  estimateGas: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFees(overrides?: Overrides): Promise<BigNumber>;

    "claimFees()"(overrides?: Overrides): Promise<BigNumber>;

    contractCreator(overrides?: CallOverrides): Promise<BigNumber>;

    "contractCreator()"(overrides?: CallOverrides): Promise<BigNumber>;

    conversionRateNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "conversionRateNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    denominator(overrides?: CallOverrides): Promise<BigNumber>;

    "denominator()"(overrides?: CallOverrides): Promise<BigNumber>;

    depositFei(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "depositFei(uint256)"(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    feesEarned(overrides?: CallOverrides): Promise<BigNumber>;

    "feesEarned()"(overrides?: CallOverrides): Promise<BigNumber>;

    fei(overrides?: CallOverrides): Promise<BigNumber>;

    "fei()"(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "swap(uint256,address,bytes)"(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;

    "usdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    usdcFeesNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "usdcFeesNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFei(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawFei(uint256)"(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawUSDC(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawUSDC(uint256)"(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawableFei(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdrawableFei(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawableUSDC(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdrawableUSDC(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimFees(overrides?: Overrides): Promise<PopulatedTransaction>;

    "claimFees()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    contractCreator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "contractCreator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    conversionRateNumerator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "conversionRateNumerator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    denominator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "denominator()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositFei(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "depositFei(uint256)"(
      amountFeiIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    feesEarned(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "feesEarned()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fei()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swap(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swap(uint256,address,bytes)"(
      amountFeiOut: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usdcFeesNumerator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usdcFeesNumerator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawFei(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawFei(uint256)"(
      amountFeiOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawUSDC(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawUSDC(uint256)"(
      amountUSDCOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawableFei(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "withdrawableFei(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawableUSDC(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "withdrawableUSDC(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
