/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestArberInterface extends ethers.utils.Interface {
  functions: {
    "fei()": FunctionFragment;
    "flashArb(uint256,uint256,address)": FunctionFragment;
    "lFeiPairCall(address,uint256,bytes)": FunctionFragment;
    "usdc()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "fei", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "flashArb",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lFeiPairCall",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "fei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flashArb", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lFeiPairCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;

  events: {};
}

export class TestArber extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestArberInterface;

  functions: {
    fei(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "fei()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    flashArb(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "flashArb(uint256,uint256,address)"(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    lFeiPairCall(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "lFeiPairCall(address,uint256,bytes)"(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    usdc(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "usdc()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  fei(overrides?: CallOverrides): Promise<string>;

  "fei()"(overrides?: CallOverrides): Promise<string>;

  flashArb(
    amountFei: BigNumberish,
    amountUsdc: BigNumberish,
    lFeiPair: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "flashArb(uint256,uint256,address)"(
    amountFei: BigNumberish,
    amountUsdc: BigNumberish,
    lFeiPair: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  lFeiPairCall(
    sender: string,
    amountFeiOut: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "lFeiPairCall(address,uint256,bytes)"(
    sender: string,
    amountFeiOut: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  usdc(overrides?: CallOverrides): Promise<string>;

  "usdc()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    fei(overrides?: CallOverrides): Promise<string>;

    "fei()"(overrides?: CallOverrides): Promise<string>;

    flashArb(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "flashArb(uint256,uint256,address)"(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: CallOverrides
    ): Promise<void>;

    lFeiPairCall(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "lFeiPairCall(address,uint256,bytes)"(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    usdc(overrides?: CallOverrides): Promise<string>;

    "usdc()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    fei(overrides?: CallOverrides): Promise<BigNumber>;

    "fei()"(overrides?: CallOverrides): Promise<BigNumber>;

    flashArb(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "flashArb(uint256,uint256,address)"(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    lFeiPairCall(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "lFeiPairCall(address,uint256,bytes)"(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;

    "usdc()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fei()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashArb(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "flashArb(uint256,uint256,address)"(
      amountFei: BigNumberish,
      amountUsdc: BigNumberish,
      lFeiPair: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    lFeiPairCall(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "lFeiPairCall(address,uint256,bytes)"(
      sender: string,
      amountFeiOut: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
